export const crimConst = {
  CRIM_FETCH_REQUEST: "CRIM_FETCH_REQUEST",
  CRIM_FETCH_SUCCESS: "CRIM_FETCH_SUCCESS",
  CRIM_FETCH_FAILURE: "CRIM_FETCH_FAILURE",
};

export const createCriminal = {
  CREATE_CRIMINAL_REQUEST: "CREATE_CRIMINAL_REQUEST",
  CREATE_CRIMINAL_SUCCESS: "CREATE_CRIMINAL_SUCCESS",
  CREATE_CRIMINAL_FAILURE: "CREATE_CRIMINAL_FAILURE",
};

export const deleteCriminal = {
  DELETE_CRIMINAL_REQUEST: "DELETE_CRIMINAL_REQUEST",
  DELETE_CRIMINAL_SUCCESS: "DELETE_CRIMINAL_SUCCESS",
  DELETE_CRIMINAL_FAILURE: "DELETE_CRIMINAL_FAILURE",
};
